_BASE_: [
  '../datasets/coco_detection_LLVIP.yml',
  '../runtime_llvip.yml',
  '_base_/optimizer.yml',
  '_base_/MSDETR_r50vd.yml',
  '_base_/damsdet_reader.yml',
]

find_unused_parameters: True
log_iter: 200
